apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kye2xy685-python 
  janus-idp.io/tekton: kye2xy685-python
  backstage.io/kubernetes-id: kye2xy685-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kye2xy685-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  