apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kye2xy685-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:7f77c55dfc8999596dd6d1aef42bc8edd28c6dcb@sha256:75c8ca069b998117b280caf65ec9ac73fc5fbe167eaa17f0e34d097ca3c264ff
          name: container-image
