apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: kye2xy685-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kye2xy685-python 
  name: kye2xy685-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: kye2xy685-python
    weight: 100 
