apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kye2xy685-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kye2xy685-python 
  name: kye2xy685-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kye2xy685-python 
